### ISSUE TITLE
How to Cite Doit

### ISSUE THREAD

**Issue by camillescott** [pydoit/doit#158]
First of all, I'd like to thank you for your time and energy spent on doit. I use it extensively in my graduate work as the core for a couple bioinformatics software projects (see https://github.com/camillescott/shmlast and https://github.com/camillescott/dammit), and I've gotten a number of people in our lab at UC Davis to start using it for workflow automation.

This falls somewhere between a feature request and a regular old question, so I figured I'd drop it here in the github tracker. I'm currently working on getting shmlast into the [Journal of Open Source Software](http://joss.theoj.org/), and I'd like to cite doit; my question is, what is the preferred method? There doesn't seem to be a DOI or preprint for it, but I'd like to give you proper credit. Would you consider giving it a DOI through a service like [Zenodo](https://zenodo.org/), or even writing up a summary paper for JOSS? I'd be willing to help out with the submission process if you'd like to pursue the latter -- they only require a couple paragraphs, and doit's documentation and testing more than satisfies all the other requirements.

Cheers,
Camille

**Comment by schettino72** [comment]
Hi Camille,

Thanks for bothering about citing doit. I dont know about the "best way" to cite.

I never heard of JOSS and I dont know what is DOI. I would not pursue this myself but would be glad if you could contribute that. Also never heard about Zenodo, if you think it is useful and are willing to work on it, please go ahead :)

Apart from the  documentation on the website once I wrote this: http://ojs.pythonpapers.org/index.php/tppm/article/view/140
Not sure it is useful to you, or how outdated it is...

If you need any kind of help just let me know, and please keep me updated on your progress.

cheers

**Comment by waisbrot** [comment]
I'm not related to the doit project, but I have written scholarly papers before.

I would not expect to see doit cited in any paper, no matter how vital it was to the work being done, because I've never seen a paper cite tools. If you use a tool and want to give it a little advertising, a footnote or an acknowledgements section is appropriate in many journal formats.

**Comment by ajasja** [comment]
@waisbrot, both [GNU parallel](https://www.gnu.org/software/parallel/) as well as [makeflow](http://ccl.cse.nd.edu/software/makeflow/)  (tools in the same category as pydoit) recive numerous citations. Also if you look through the method section of any of my papers you will see all the software tools cited:
![image](https://cloud.githubusercontent.com/assets/19926/21472988/6356fbda-caf3-11e6-97ee-a1d7ef0aa060.png)

But I guess the number of citations doesn't matter for the pydoit project, since no funding is obtained via scientific grants.

**Comment by schettino72** [comment]
Hey guys. This is not the best place (or the right audience) to discuss how a paper should be written. I would like those who wish cite *doit*, to do in a proper way. If you want to discuss if should be done at all or not, please find another channel.

**Comment by schettino72** [comment]
Added https://zenodo.org/record/4892136
