### ISSUE TITLE
Graphviz plugin

### ISSUE THREAD

**Issue by MaxHalford** [pydoit/doit#176]
Hello,

First of all I would like that I'm really enjoying using doit! I'm using it for a data science pipeline and I find so much more flexible than a Makefile.

I looked at the networkx plugin for displaying a DAG of the different tasks/files but I didn't find it very "pretty". Implementing a plugin doesn't seem too difficult; I was wondering if it might be worthwhile to **implement a Graphviz plugin**.

As mentioned in the contribution guidelines it seems to discuss it here first, any thoughts?

**Comment by schettino72** [comment]
Hi Max,

Yes, the networkx plugin did not go very far. I think a DAG output with graphviz would be very welcome and not hard to implement. 

Just note that because doit is very dynamic its output might not be 100% complete if you use some more advanced features. I suggest you take a look at the `info` command implementation. good luck.
 
cheers,

**Comment by justinmcgrath** [comment]
Has this been pursued? This would be quite a nice feature to have.

It seems that producing a DOT file would be a flexible approach. Several programs can plot those, including GraphViz and networkx.

**Comment by MaxHalford** [comment]
I simply haven't had time to get into it for personal reasons.

Sure, it would be good practice to separate the DOT generation and actually rendering the output.

**Comment by schettino72** [comment]
closing this as it now has it own repo. released on pypi as `doit-graph`
