### ISSUE TITLE
parametrize script name

### ISSUE THREAD

**Issue by rbdixon** [pydoit/doit#184]
I'm building a tool which uses doit's command line tool as the primary user interface. doit is well abstracted so this has been very easy to do. There are a few places where the "doit" name continues to peek out such as the output of the "info <task>" command:

```
$ <mycommand> help info
Purpose: show info about a task
Usage:   doit info TASK
```

https://github.com/pydoit/doit/blob/master/doit/cmd_base.py#L127

Would you be open to merging a PR that makes the binary name a configurable option using `DOIT_CONFIG`? If so I'll hack away at it.

**Comment by schettino72** [comment]
Hi rbdixon,

Which tool are you building? Open source?

I would like to see a standard way to get the binary name. Adding a config option is OK but I would like to have an internal API so that **all** commands access this name in the same way.

For example if you look at `cmd_completion` the binary name is simply taken from the `sys.argv[0]`.
In the class `DoitMain` there is a class attribute `BIN_NAME`, are you sub-classing `DoitMain`?

So the preferred solution would be to just use `DoitMain.BIN_NAME`. If you feel the need to set this value from a config value that is fine. But commands should rely on `DoitMain.BIN_NAME` and not read the config value directly. makes sense?

cheers

**Comment by schettino72** [comment]
I fixed the name `doit` showing up on docs. On some error messages I chose to still display `doit`. Please let me know if missed somewhere...

As for configuring through `DOIT_CONFIG`, I do not know what the use-case would be.
For my tests I had a file like:

```
#! /usr/bin/env python3

import sys
from doit.doit_cmd import DoitMain
sys.exit(DoitMain().run(sys.argv[1:]))
```

If there is a use-case for `DOIT_CONFIG` it can be added, just let me know...

**Comment by rbdixon** [comment]
Thank you for the `bin_name` parameter. That's perfect and I'll have no issue slipping that into the tool we have up and running now.
