### ISSUE TITLE
Run command implementation question

### ISSUE THREAD

**Issue by moltob** [pydoit/doit#216]
I am implementing a new Reporter and I am trying to evaluate `ConsoleReporter.show_out`. Debugging the result was a bit unexpected, essentially resulting from this line (currently 213) in `cmd_run.py`:

```python
show_out = use_verbosity < 2  # show on error report
```

`show_err` is always `True`. I understood `show_out` would become active in case of a _higher_ verbosity level, so I would expect:

```python
show_out = use_verbosity > 1
```

Am I thinking the wrong way or is this a small issue?

**Comment by schettino72** [comment]
The variable meaning is documented:

`    @ivar show_out (bool): include captured stdout on failure report`

The reason is that if the output has already been shown while the task was running,
it should no appear again. 

Actually I want to make this behaviour of the output being displayed twice or not to be configurable.
See: https://github.com/pydoit/doit/issues/140
