### ISSUE TITLE
Python custom clean actions are not executed when the "dryrun" flag -n is set 

### ISSUE THREAD

**Issue by toschoch** [pydoit/doit#245]
Hi,
First, thanks a lot for this great package. I'll love it!! I'm currently using doit for automization of my data analysis tasks. 
I just noticed a small issue, that I think it might be unintended. 
When I write a custom clean action of a target there is a parameter "dryrun" passed to the action (nicely illustrated in clean_targets implementation [task.py source](https://github.com/pydoit/doit/blob/62335b05473193303d6ecb5524d65bf1a5a50d7e/doit/task.py#L570))
Anyway, if `doit clean -n  <taskname>` is executed the clean action is not called at all.

`dodo.py`
```python
import os

def create_file(filename):
    with open(filename,'w+') as fp:
        fp.write('Hello World\n')

def my_cleaner(filename, dryrun):
    msg = "remove '{}'...".format(filename)
    if dryrun:
        msg = "would " + msg
    print(msg)
    if not dryrun and os.path.exists(filename):
        os.remove(filename)

def task_hello():
    """ creates a "Hello World" file """

    filename = 'test.txt'

    task = {
        "actions" : [(create_file,(filename,))],
        "targets" : [filename],
        "clean"   : [(my_cleaner,(filename,))],
        "uptodate": [True],
    }

    return task
```
and than in the console
```
>>> doit hello
.  hello
>>> doit clean -n hello
hello - executing 'Python: function my_cleaner'
```
however I would expect the following:
```
>>> doit clean -n hello
hello - executing 'Python: function my_cleaner'
would remove 'test.txt'...
````

**Comment by schettino72** [comment]
Is this documented anywhere or you just took from the code?

Looking at my code it seems that indeed it tries to support your use-case. 
But actually on dry-run your custom clean functions a re not used at all. see [1]

So now the problem is that, if we always call the clean action I suspect most people do not use the `dryrun` param, so their clean would be executed even on dryrun :sweat: 

So I suggest the fix would be that if a function does not take a `dryrun` parameter we keep the current behaviour. And always call the clean action if `dryrun` is present and hope the custom clean action handles the dryrun parameter correctly.

What do you think?

[1] https://github.com/pydoit/doit/blob/62335b05473193303d6ecb5524d65bf1a5a50d7e/doit/task.py#L486
