### ISSUE TITLE
Add a command to recompute dependencies state.

### ISSUE THREAD

**Issue by saimn** [pydoit/doit#25]
When changing `check_file_uptodate` the states of dependencies are dropped, so all the tasks are considered out-of-date. This is an issue when the tasks takes a long time to run, and if the file deps  / targets are already existing. 
So I would like to add a command which recompute the states of dependencies without executing the tasks. I think I will take example on the forget command, to find all tasks/subtasks and call `self.dep_manager.save_success` for each task. Seems reasonable ?
Also suggestions for the cmd name are welcome ;-), something like `rebuilddb` ?

**Comment by schettino72** [comment]
I guess it is reasonable. You just need to pay attention that tasks save other values not only information about file_dep... Worse than that if you just call `save_success()` you will remove previously saved values, so I would not use this function.

The command name should not be called `rebuilddb` because it is not being completely rebuilt!
`set-file-dep-as-uptodate` is the best description but too long so what about `reset-dep`?

**Comment by saimn** [comment]
Ah yes indeed, so I need to update the checker class name, the list and the state of file deps. `reset-dep` seems ok, thanks.
