### ISSUE TITLE
doit reruns each time

### ISSUE THREAD

**Issue by tcholewik** [pydoit/doit#271]
Hi I'm still learning this library so its very likely that I did something wrong, but right now it seems that doit reruns all tasks every single time.

Initially I saw this behavior with code that a lot more complicated but then wrote example below to debug this issue, and I still see it.

```
def task_experiment():
    def touch():
        open('test','w')
    return {
        'actions': [touch],
        'targets': ['test']
    }
```

Then I run:

> doit run --file=dodo_sample.py
>.  experiment
> doit run --file=dodo_sample.py
>.  experiment
> doit run --file=dodo_sample.py
>.  experiment

Its very likely that I'm missing something obvious but I'm just not sure what it is.

Contents of my doit related files:
.doit.db.bak 
>'experiment', (0, 56)

.doit.db.dir
>'experiment', (0, 56)

.doit.db.bat
>{"_values_:": {}, "checker:": "MD5Checker", "deps:": []}

My system:
doit 0.31.1
Python 3.6.6
Win10

**Comment by tcholewik** [comment]
Also running strace produces:
>. experiement
>. strace_report

**Comment by tcholewik** [comment]
One more thing I tried using --chcek_file_uptodate with both timestamp and md5 options and they produce same outcome.

**Comment by tcholewik** [comment]
After couple hours of reasearch I found the problem.
Target is not file dependency, I had to specify file_dep to keep my task from reruning.

**Comment by mshabunin** [comment]
I believe this issue should be reopened and documentation should be changed.

Documentation does not mention that empty `file_dep` implies that target will be always executed, for example here: https://pydoit.org/tasks.html#targets Furthermore, the documentation contains example of task with empty `file_dep` field (https://pydoit.org/tasks.html#execution-order (_create_)) which behaves like that. The expected behavior can be achieved by setting `uptodate` property to `True`, but it should be reflected in the documentation (note in "Tasks" section with link to "More on dependencies").
