### ISSUE TITLE
Document doit integration into another program.

### ISSUE THREAD

**Issue by paternal** [pydoit/doit#357]
# Problem
The [Use cases](https://pydoit.org/usecases.html) page has an example [Extend your project by doit features](https://pydoit.org/usecases.html#extend-your-project-by-doit-features):
> Your own python project would need features of doit, but you cannot ask your users to call doit on command line?
> 
> Simply integrate doit functionality into your own command line tool and nobody will notice where it comes from.

The [Success stories](https://pydoit.org/stories.html) page describes [how Nikola internally uses doit](https://pydoit.org/stories.html#nikola).

But none of those stories explains *how* to do this: every piece of documentation seems to be about using doit from the command line.

# Solution

Write documentation about how to integrate doit into you own project (without any assumption about command line), i.e.:
- how to define tasks;
- how to find/gather tasks;
- how to run tasks.

I would have tried to submit a pull request, but I tried to understand this by reading the documentation and source code, and I couldn't…

**Comment by schettino72** [comment]
The individual parts are documented.  Mostly in https://pydoit.org/extending.html

Sure adding a HOW-TO section in documentation is long due to be written... Also planned to cover this in part 4 of tutorial #123

Many years ago I wrote a blog post with a simple example. Probably has some outdated API but should be good enough to have an idea: http://blog.schettino72.net/posts/power-up-your-tools.html

**Comment by schettino72** [comment]
By the way, if you update the blog post above I would gladly accept a PR in a format of HOW-TO section for the docs/website.
