### ISSUE TITLE
cmd-action substitution keys should include (almost) all task properties

### ISSUE THREAD

**Issue by ankostis** [pydoit/doit#38]
The most important task-properties are the "dependency fields" and these are good to have them in the substitution-dictionary for debugging purposes.
Currently even a simple `echo %(name)s` cmd-action does not work.

As a side note, it would facilitate the user if at action.py@, ine:248 it catches `KeyError` and prints the original cmd's format-text causing the problem.

**Comment by schettino72** [comment]
There is a more general way that you can get any info from a task. 

```
from doit.action import CmdAction

def task_hello():
    """hello cmd """

    def create_cmd_string(task):
        return "echo hi my name is {}".format(task.name)

    return {
        'actions': [CmdAction(create_cmd_string)],
        'verbosity': 2,
        }
```

The error message includes the task name. That should be enough for you to find the mistake...
Anyway if you want you think it is worth to print the original cmd string, please send a PR :)

**Comment by ankostis** [comment]
I knew that already, but at least for the `name` it should be more straight-forward to get it.

I can provide a PR for both (1. add name in keys, report string) if you that is not a problem.

**Comment by schettino72** [comment]
> I knew that already, but at least for the name it should be more straight-forward to get it.

The problem is that these magic method are not exactly "free", it would not be nice to it for CmdAction but not for PythonAction... and then you have the problem that once you have a magic argument the user can not use an argument with the same name in the callable...

> I can provide a PR for both (1. add name in keys, report string) if you that is not a problem.

Sorry, I think this is not common enough usage and although not as simple as you wish the alternative in my example is quite simple too. So I would prefer to leave doit without another magic argument.
