### ISSUE TITLE
Priority for the verbosity config

### ISSUE THREAD

**Issue by saimn** [pydoit/doit#52]
Hi,
I have a `DOIT_CONFIG` with verbosity set to 1 (the default value iirc), and I would like to set verbosity to 2 for one of my tasks, but setting verbosity to 2 in this task attributes doesn't work, the value from DOIT_CONFIG seems to have the highest priority.
I would have though that the priority order for this kind of setting would be : cli options > task attribute > global DOIT_CONFIG value, but it seems it is not the case. Looking at the code, I did not found where the verbosity from the task attributes is used. It seems that something is missing here https://github.com/pydoit/doit/blob/master/doit/cmd_run.py#L195

**Comment by schettino72** [comment]
Your expectation makes sense but the command implementation does not have access to details from where a value came from (if it came from command line or DOIT_CONFIG)...

The `verbosity` option is special because it can be overwritten by a task, I guess no other option has this problem. 

The easiest way is to set the default in the `Task` class not in `DOIT_CONFIG`. The code you point to is exactly to handle that. In your dodo.py do something  like:

```
from doit.task import Task
Task.DEFAULT_VERBOSITY = 2
```

Or we could add another option "default-verbosity"...

**Comment by saimn** [comment]
Actually it is not in the code I was linking, I forgot one piece of the puzzle: `Task._get_out_err`. And with this, as you said, if I modify `Task.DEFAULT_VERBOSITY` instead of using `DOIT_CONFIG`, it does what I expect.
Maybe `Task.DEFAULT_VERBOSITY` could be modify by `load_doit_config` if verbosity is present ? It is not ideal, but currently if `DOIT_CONFIG['verbosity']` is used, `task.verbosity` is ignored.

**Comment by schettino72** [comment]
I dont like the idea of modifying `Task.DEFAULT_VERBOSITY` based on where the `verbosity` option was set. The priority order is `verbosity` option > task's verbosity > `Task.DEFAULT_VERBOSITY`

If you wish to add a new command option `default_verbosity` I would be ok with that. In this case, please re-open this issue and change the title.
