### ISSUE TITLE
Ability to select tasks using a shortcut

### ISSUE THREAD

**Issue by lelit** [pydoit/doit#73]
Usually tasks are identified by long names like "do_something_on_this", "build_documentation". Thankfully we have tab-completion that makes it less annoying to build the command line...

I think it would be nice to have another, possibly quicker even if mnemonic way to select a task, once you know its name: what about being able to say `doit dsot` or `doit bd` to run the hypothetic tasks mentioned above?

An initial, proof-of-concept implementation is lelit/doit@a540533fcaa83d6c7560e2940c4cbc6ad6bfc731

**Comment by schettino72** [comment]
I dont see much people being interested on this. But I might be wrong... and even if you are the only interested on this, you should be able to achieve this without forking doit.

Can you implement this by modifying the `run` command instead of making changes into `control.py`? If you change the `run` command you could use/enable your custom command as a plugin.
If this ever gets merged it will need to be enabled by command line param (not enabled by default).

Once I thought about implementing something like py.test keyword selection with `-k`. 

Another option for you is to create alias tasks manually, just create a task with no action and a `task_dep` to the task be aliased.

So I suggest you pursue this as separate command plugin. Once you get it, I might re-consider bringing the changes into `doit` core. Just keep me updated...

**Comment by lelit** [comment]
No problem, I'll try to understand what you are suggesting. Otherwise I will try to get there by monkey patching doit, hopefully from within my dodo.py.

I implemented the very same mechanism on top of paver, and the users were quite happy of it. Paver has a `TaskFinder` component that one can easily inject into the system.

**Comment by schettino72** [comment]
Look at this: http://pydoit.org/extending.html#command-customization

You can create a new command by sub-classing the existing `CmdRun`. Wrap the `_execute()` method adding the tasks aliases, then call the original `CmdRun._execute()`. Should be easy :)

**Comment by lelit** [comment]
Thank you, will try!

**Comment by lelit** [comment]
Is there a way, for a task, to forward command line arguments to the task_dep tasks?

**Comment by schettino72** [comment]
> Is there a way, for a task, to forward command line arguments to the task_dep tasks?

No. I guess I gave you a bad suggestion...

I have another (better) idea. Subclass cmd_run.py:Run class and overwrite the method `_execute()`:

- go through `self.task_list` and create your list of abbreviations/shortcuts
- replace any abbreviations found in `self.sel_tasks`
- call original `Run._execute()`

In other words, you will just process and modify the user input so that it looks like a "normal" input with full task names. what do you think?

**Comment by lelit** [comment]
For the record, I opted to create a simple bash alias to implement the functionality I need:
```bash
function dt() {
    local shortcut=$1
    local helpopt=$2
    local expr_rx=$(echo $shortcut | sed 's/\(.\)/\1[^_]*_/g')
    declare -A seen
    shift
    doit list | while read papabile helpdoc
    do
        case $shortcut in
            list)
                local alias=$(echo $papabile | sed 's/\(.\)[^_]*_*/\1/g')
                if test -z "${seen[$alias]}"
                then
                    echo -e "$alias, $papabile\n\t$helpdoc\n"
                    seen[$alias]=t
                fi
                ;;
            *)
                if test "$papabile" = "$shortcut" -o $(expr "$papabile" : "$expr_rx*") -gt 0
                then
                    if test "$helpopt" = "-h" -o "$helpopt" = "--help"
                    then
                        doit help $papabile
                    else
                        doit $papabile $*
                    fi
                    seen[$papabile]=t
                    break
                fi
                ;;
        esac
    done
}
complete -F _doit dt
```

It customizes the `list` command, showing something like
```
$ dt list
db, dc_build
	Rebuild needed containers.

de, dc_execute
	Execute an interactive command within a running container.

gacru, git_auto_commit_ref_updates
	Automatically commit submodules ref changes.
```

and understands an handy alternative to `help`:

```
$ dt gacru -h
git_auto_commit_ref_updates  Automatically commit submodules ref changes.
  -n, --dry                 Do not actually run the task, just show what would happen
  -i, --ignore-dirty        Ignore dirty submodules
```

**Comment by schettino72** [comment]
cool. Although I cant say I understand your bash script...
Does it work completely without any change in doit code?

Do you have this in a separate repository? 
Feel free to add link to this somewhere in the docs (submit a PR) or the [wiki](https://github.com/pydoit/doit/wiki/powered-by-doit)

**Comment by lelit** [comment]
Yes, it does not require any changes to `doit`. 

It works by *parsing* the output of `doit list`: with a simple `sed` script it computes a *regular expression* that matches only the initial letter of a *underscore-separated-list-of-words*; if that matches one of the task names, it executes it passing all the remaining arguments when the second argument (that is, the one right after the task name) is not either `-h` or `--help`: in such case it executes `doit help original_task_name`.

I will add it to the wiki.

**Comment by lelit** [comment]
Eduardo, I created a [new page](https://github.com/pydoit/doit/wiki/Shell-wrapper-providing-task-name-shortcuts) as requested: is it good enough?

**Comment by schettino72** [comment]
> that allowed me to say paver ddfm as an alias for paver do_that_for_me

I guess you mean `paver dtfm`, notice a `T` in the second letter.

Looks good to me. Although I would cut the history and go straight to the point without mentioning paver or the original ticket number (at least in the beginning of the text).

I would also add a link to this page from the page that has a list of projects (https://github.com/pydoit/doit/wiki/powered-by-doit)

thanks
